### ISSUE TITLE
Ringer mode issues

### ISSUE THREAD

**Issue by gaelmarhic** [udacity/AdvancedAndroid_Shushme#2]
Hi!

When trying this solution final code on my phone (running with Android N), I ran into some issues which made the app crash:

1) Some packages in the GeofenceBroadcastReceiver file have not been imported, so that it does not let compile.

2) The permission for the ACCESS NOTIFICATION POLICY is not present in the Manifest.xml file.
 <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>

3) Since when we want to change the Ringer mode we want to make sure that Notification Policy Access is granted (in case our SDK is 24 or greater), I think the appropriate code should be:

if (android.os.Build.VERSION.SDK_INT < 24 ||
                (android.os.Build.VERSION.SDK_INT >= 24 && nm.isNotificationPolicyAccessGranted())) 
...

and not
if (android.os.Build.VERSION.SDK_INT < 24 ||
                (android.os.Build.VERSION.SDK_INT >= 24 && !nm.isNotificationPolicyAccessGranted())) 
...

I actually removed the "!", since in the current version of the code we try to change the Ringer mode status when the permission is not granted...

Thanks for your great tutorials guys!

Kind regards,

Gaël

**Comment by dharanad** [comment]
Add `<uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>` in the manifest file.

**Comment by hrishikesh-kadam** [comment]
All bugs fixed in - https://github.com/udacity/AdvancedAndroid_Shushme/pull/12

**Comment by moharidy** [comment]
thanks all but i still have an issue with the ringer issue, when the geofences switch is disabled the silent mode does not get disabled and the phone still continue on silent mode? any suggestion ?
